import uuid
from datetime import datetime
from enum import Enum
from typing import List, Optional, Union, Dict, Any, Literal
from pydantic import BaseModel, Field
from enum import Enum

class BlockType(str, Enum):
    TEXT = "text"
    TABLE = "table"

class DocBlock(BaseModel):
    id: str = Field(default_factory=lambda: "") # Will be set by hashing content
    block_type: BlockType
    content: str
    section_path: List[str]
    page_num: Optional[int] = None

class TextBlock(DocBlock):
    block_type: BlockType = BlockType.TEXT

class TableBlock(DocBlock):
    block_type: BlockType = BlockType.TABLE

class UFLRow(BaseModel):
    row_id: str
    entity_id: str
    entity_name_raw: str
    metric_name: str
    value: Optional[float]
    unit: Optional[str] = None
    scale_factor: float = 1.0
    period: str
    doc_section: str
    source_chunk_id: str
    nuance_note: Optional[str] = None
    confidence: float
    related_entity_id: Optional[str] = None

class EntityMetadata(BaseModel):
    canonical_id: str
    official_name: str
    cik: Optional[str] = None
    aliases: List[str] = []

class ScrapedFact(BaseModel):
    metric_name: str
    value: Optional[Union[float, str]]
    unit: Optional[str] = "USD"
    period: Optional[str] = None
    nuance_note: Optional[str] = None
    related_entity: Optional[str] = None
    confidence: float

class FactExtractionResponse(BaseModel):
    facts: List[ScrapedFact]

# --- Navigator Models ---

class UFLFilter(BaseModel):
    """Configuration for the structured data lookup."""
    entity_ids: List[str] = Field(..., description="Canonical IDs (e.g., 'ID_AAPL')")
    metric_keywords: List[str] = Field(..., description="List of potential column headers to search for (e.g., ['Net Sales', 'Revenue'])")
    years: List[str] = Field(..., description="Specific years mentioned (e.g., ['2023', '2022']). Leave empty if asking for 'current' or 'trend'.")
    nuance_focus: Optional[str] = Field(None, description="Keywords for nuance filtering (e.g., 'Restated', 'Adjusted')")

class RetrievalPlan(BaseModel):

    """The Master Plan (Clues) generated by the Navigator SLM."""

    

    ufl_query: Optional[UFLFilter] = Field(None, description="Clues for the structured database lookup.")

    vector_hypothesis: str = Field(..., description="A hypothetical sentence or table header that would appear in the document containing the answer.")

    vector_keywords: List[str] = Field(..., description="3-5 key search terms for BM25/Keyword search.")

    reasoning: str = Field(..., description="Brief explanation of the translation logic.")